### PR TITLE
Simplify & WebExtensions

### PR DESCRIPTION
**Pull request by mart-e**
Follow [WebExtension](https://developer.mozilla.org/en-US/Add-ons/WebExtensions) specifications.
This way, we can finally get rid of Chrome (and reach the goal of world domination)

Add the triple click feature and refactoring made by @JKE-be

Will publish an extension on https://addons.mozilla.org/ as soon as this is merged

### CODE REVIEW

**Comment by mart-e** [comment]
@JKE-be where does the web icon comes from? It is smaller than the other ones

**Comment by JKE-be** [comment]
I forked the project with old icon, meanwhile pga make the new monkey (with new size and a bit different ) back... 
image

Perso, I never used the triple click to switch from backend/frontend...
Probably that a magic function like: 
```
$("input#login").val('admin');
$("input#password").val('admin');
$('form.oe_login_form').submit();
```
Will be a better choice ;)

**Comment by mart-e** [comment]
Hmm not a bad idea actually.
Ok I will remove the triple click to keep only the refactoring

**Comment by jat-odoo** [comment]
@mart-e @JKE-be 
For Auto login feature,
We are updating [runbot extension](https://chrome.google.com/webstore/detail/odoo-runbot/jllbemjkkabaohnjcnajhflahlkehmlf) and this feature will covered in this.
test


Once this PR will merge, we will launch for Firefox soon.
Thanks for your work. :+1:

**Comment by mart-e** [comment]
Oh actually that was easier to do than I expected :) 
https://addons.mozilla.org/en-US/firefox/addon/odoo-debug/

**Comment by mart-e** [comment]
Thanks @jat-odoo !

**Pull request merged**
